### ISSUE TITLE
Fetching from watch Problem and think of what to do with other watches

### ISSUE THREAD

**Issue by parteekcoder** [aditygrg2/shayan#90]

**Comment by aditygrg2** [comment]
- User will be able to setup watch only if it is logged in, a new error material design is set up.
- Other bands like Samsung, and Garmin have a new popup now
- The homepage widget is now updated dynamically, if user have not setup watch then only it will show up
- The issue with Google Fit is completely resolved
- Earlier, there was an issue where the account sync was not appropriately maintained when logged out, the previous google fit account were updating - fixed
- Profile page now consists of an option to revoke the watch permissions.

@parteekcoder @Sumitkevlani  Please use new accounts from now. All previous are deleted.

**Comment by parteekcoder** [comment]
Thanks @aditygrg2 for this fix
